version: '3.9'
services:
  financy:
    image: motherdock/java:SpringBootRunner
    container_name: SpringAppEasyMenu
    ports:
      - "8083:8080"
    volumes:
      - /home/ubuntu/app/easymenu:/app
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - javaAppNet

networks:
  javaAppNet:
   external: true